export enum Role {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  COMPANY_OWNER = 'COMPANY_OWNER',
  COMPANY_MANAGER = 'COMPANY_MANAGER',
  EMPLOYEE = 'EMPLOYEE'
}

export enum CompanySize {
  MICRO = 'MICRO',
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE'
}

export enum IndustryType {
  IT = 'IT',
  FINANCE = 'FINANCE',
  HEALTHCARE = 'HEALTHCARE',
  EDUCATION = 'EDUCATION',
  RETAIL = 'RETAIL',
  MANUFACTURING = 'MANUFACTURING',
  CONSTRUCTION = 'CONSTRUCTION',
  CONSULTING = 'CONSULTING',
  OTHER = 'OTHER'
} 